### ISSUE TITLE
unable to log in

### ISSUE THREAD

**Issue by Sungod3000** [themexpert/onepager#97]
Hi,

Im just started a fresh installation and now all im getting when I enter editor is "could not save" and "unable to sync, make sure you are logged in" also on my page start blank and corporate1 always answer with "failed to insert layout" corporate1 somehow sticks but then in the editor the above mentioned happens. 
any tips or trick for this?

**Comment by nadimtuhin** [comment]
@Sungod3000 looks like its an issue with other plugins and themes. Can you share your website url through email? my email is nadimtuhin @ themexpert . com

Optional Checks:
1. disable all plugins except onepager and check if the error resolves
2. change the theme and check if the error resolves

If you do not want to change theme or plugin
1. open onepager editor
2. open google chrome network tab (how to open https://www.youtube.com/watch?v=AXGB4tIRNgM)
3. click on xhr on network tab
4. click add block, then click on a block image
5. then send me a screenshot like this
![test](https://cloud.githubusercontent.com/assets/3125771/10476094/96329fb8-726c-11e5-8f04-e196f2f5cb3a.jpg)

**Comment by nadimtuhin** [comment]
fixed

**Comment by Mamadiarra** [comment]
It doesn't work online .
Please help me

**Comment by test86** [comment]
@nadimtuhin 

Hi, could you please help me?
I have exactly the same problem. "unable to sync, make sure you are logged in"
I have 1 free web hosting with: Wordpress last version (4.7.2) and last version of Onepager (1.2.5).
I just add the new page onepage.php in the theme folder, and everthing is working perfect. (thank you by the way)

Yesterday i bought a new web hosting in ovh.com.
ps: The domain name is with another compagny.
Same install... Fresh wordpress and onepager only.

But on that web hosting i have this message "failed to insert layout" when i click on start blank or corporate1.
Then when I click on load editor (only when I see it, because not every time) then I click on add block and I have this:
In green color: New section added.
And directly in red color: Unable to sync. Make sure you are logged in.

Could you please help me, it's very urgent.
Thank you in advance.
